### ISSUE TITLE
Problem expanding $REFGENIE env var 

### ISSUE THREAD

**Issue by jpsmith5** [databio/pepatac#115]
@vreuter 

Have set `REFGENIE` to my refgenie.yaml.  Looks like either PEPATAC when it  performs `_add_resources` (line 503) is not expanding the path there, or in `refgenie` proper when it's loading the config file it is not expanding?

My $REFGENIE:
```
$ echo $REFGENIE
/sfs/lustre/scratch/jps3dp/tools/databio/refgenie.yaml

```

```
Changed status from initializing to running.

Loading config file: pipelines/pepatac.yaml

Config file path isn't a file: ${REFGENIE}
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1550, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 503, in main
    res = _add_resources(args, res)
  File "pipelines/pepatac.py", line 457, in _add_resources
    rgc = RGC(select_genome_config(res.get("genome_config")))
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/helpers.py", line 20, in select_genome_config
    return yacman.select_config(filename, conf_env_vars or CFG_ENV_VARS)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/yacman/yacman.py", line 92, in select_config
    raise IOError(config_filepath)
OSError: ${REFGENIE}
Pipeline status: running
Starting cleanup: 0 files; 0 conditional files for cleanup
```

Potentially relevant portion of `refgenie`

```
print(default_config_file())

config_file = args.config_file
import logging
if config_file:
        if os.path.isfile(config_file):
            #looks good!
            pass
        else:
            logging.debug("Config file path isn't a file: {}".
                          format(config_file))
            args.config_file = default_config_file()
```

**Comment by nsheff** [comment]
Is this related to https://github.com/pepkit/attmap/issues/37

@jpsmith5 can you confirm you have `attmap` >= 0.11 ?

**Comment by jpsmith5** [comment]
```
$ pip show attmap
Name: attmap
Version: 0.12.4
Summary: Multiple access patterns for key-value reference
Home-page: https://github.com/pepkit/attmap/
Author: Nathan Sheffield, Vince Reuter
Author-email: None
License: BSD2
Location: /home/jps3dp/.local/lib/python2.7/site-packages
Requires: ubiquerg
```
```
$ pip3 show attmap
Name: attmap
Version: 0.12.4
Summary: Multiple access patterns for key-value reference
Home-page: https://github.com/pepkit/attmap/
Author: Nathan Sheffield, Vince Reuter
Author-email: None
License: BSD2
Location: /home/jps3dp/.local/lib/python3.6/site-packages
Requires: ubiquerg

```

**Comment by vreuter** [comment]
Sorry for the trouble @jpsmith5 ; this will be solved in the next point release of `attmap`. [Here's the ticket](https://github.com/pepkit/attmap/issues/59) if you want to track.

**Comment by nsheff** [comment]
if we can confirm that this solves it, then this is worth another attmap point release (and update the pepatac requirements).

**Comment by vreuter** [comment]
OK, do you want to try with what's now on `attmap`'s `dev` branch, or do you want me to release 0.12.5 and then just try with that release version?

**Comment by jpsmith5** [comment]
Still see it.

```
$ pip show attmap
Name: attmap
Version: 0.12.5
Summary: Multiple access patterns for key-value reference
Home-page: https://github.com/pepkit/attmap/
Author: Nathan Sheffield, Vince Reuter
Author-email: None
License: BSD2
Location: /sfs/qumulo/qhome/jps3dp/.local/lib/python3.6/site-packages
Requires: ubiquerg
Required-by: yacman, refgenconf, piper, peppy, loopercli, divvy
```

```
Changed status from initializing to running.

Loading config file: pipelines/pepatac.yaml

Config file path isn't a file: ${REFGENIE}
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1550, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 503, in main
    res = _add_resources(args, res)
  File "pipelines/pepatac.py", line 457, in _add_resources
    rgc = RGC(select_genome_config(res.get("genome_config")))
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/helpers.py", line 20, in select_genome_config
    return yacman.select_config(filename, conf_env_vars or CFG_ENV_VARS)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/yacman/yacman.py", line 92, in select_config
    raise IOError(config_filepath)
OSError: ${REFGENIE}
Pipeline status: running
Starting cleanup: 0 files; 0 conditional files for cleanup

```

**Comment by nsheff** [comment]
does that fix it @vreuter ?

**Comment by vreuter** [comment]
It makes an additional improvement to `PathExAttMap`s, but there's no test case for this issue.

**Comment by jpsmith5** [comment]
Reinstalled from dev. Same issue.

```
Config file path isn't a file: ${REFGENIE}
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1550, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 503, in main
    res = _add_resources(args, res)
  File "pipelines/pepatac.py", line 457, in _add_resources
    rgc = RGC(select_genome_config(res.get("genome_config")))
  File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/helpers.py", line 20, in select_genome_config
    return yacman.select_config(filename, conf_env_vars or CFG_ENV_VARS)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/yacman/yacman.py", line 92, in select_config
    raise IOError(config_filepath)
OSError: ${REFGENIE}
```

**Comment by vreuter** [comment]
The change is only in the `vreuter` remote, not `pepkit`

**Comment by vreuter** [comment]
Oh, nevermind; apparently I did already put that on `pepkit`.

**Comment by vreuter** [comment]
Anyway, happy to test it for a specific case once one's presented.

**Comment by vreuter** [comment]
```
(py3.5) vr @ ~/code/attmap
dev└─ $ cd ../pypiper
(py3.5) vr @ ~/code/pypiper
master└─ $ git pull upstream master 
From github.com:databio/pypiper
 * branch            master     -> FETCH_HEAD
Already up-to-date.
(py3.5) vr @ ~/code/pypiper
master└─ $ pip install --upgrade ./
Processing /home/vr/code/pypiper
Requirement already satisfied, skipping upgrade: attmap>=0.12.4 in /home/vr/venvs/py3.5/lib/python3.5/site-packages (from piper==0.11.1) (0.12.5)
Requirement already satisfied, skipping upgrade: pyyaml>=5 in /home/vr/venvs/py3.5/lib/python3.5/site-packages (from piper==0.11.1) (5.1)
Requirement already satisfied, skipping upgrade: psutil in /home/vr/venvs/py3.5/lib/python3.5/site-packages (from piper==0.11.1) (5.4.8)
Requirement already satisfied, skipping upgrade: ubiquerg>=0.2.1 in /home/vr/venvs/py3.5/lib/python3.5/site-packages (from attmap>=0.12.4->piper==0.11.1) (0.4.3)
Building wheels for collected packages: piper
  Building wheel for piper (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-s288bts6/wheels/a1/09/fd/26ee3c3a763cc228cb42e1eff5bca720ee60ae0234d7ae3b61
Successfully built piper
Installing collected packages: piper
  Found existing installation: piper 0.11.1
    Uninstalling piper-0.11.1:
      Successfully uninstalled piper-0.11.1
Successfully installed piper-0.11.1
(py3.5) vr @ ~/code/pypiper
master└─ $ ipython
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: quit                                                                                                                                                                                                
(py3.5) vr @ ~/code/pypiper
master└─ $ cd ../attmap/
(py3.5) vr @ ~/code/attmap
dev└─ $ git pull upstream dev 
From github.com:pepkit/attmap
 * branch            dev        -> FETCH_HEAD
Already up-to-date.
(py3.5) vr @ ~/code/attmap
dev└─ $ pins
Processing /home/vr/code/attmap
Requirement already satisfied, skipping upgrade: ubiquerg>=0.2.1 in /home/vr/venvs/py3.5/lib/python3.5/site-packages (from attmap==0.12.5) (0.4.3)
Building wheels for collected packages: attmap
  Building wheel for attmap (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-f821t__f/wheels/82/18/97/235b04920f1a41148d19767a9a952491b7a58b9f11863598c1
Successfully built attmap
Installing collected packages: attmap
  Found existing installation: attmap 0.12.5
    Uninstalling attmap-0.12.5:
      Successfully uninstalled attmap-0.12.5
Successfully installed attmap-0.12.5
(py3.5) vr @ ~/code/attmap
dev└─ $ ipython
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pypiper import PipelineManager as PM                                                                                                                                                           

In [2]: pm = PM("testing", config_file="/home/vr/code/pepatac/pipelines/pepatac.yaml", outfolder="/home/vr/tmpout")                                                                                         
Removed existing flag: '/home/vr/tmpout/testing_failed.flag'
Warning: You're running an interactive python session. This works, but pypiper cannot tee the output, so results are only logged to screen.
### [Pipeline run code and environment:]

*              Command:  `/home/vr/venvs/py3.5/bin/ipython`
*         Compute host:  nkc
*          Working dir:  /home/vr/code/attmap
*            Outfolder:  /home/vr/tmpout/
*  Pipeline started at:   (06-06 16:27:04) elapsed: 0.0 _TIME_

### [Version log:]

*       Python version:  3.5.2
*          Pypiper dir:  `/home/vr/venvs/py3.5/lib/python3.5/site-packages/pypiper`
*      Pypiper version:  0.11.1
*         Pipeline dir:  `/home/vr/venvs/py3.5/bin`
*     Pipeline version:  None

### [Arguments passed to pipeline:]


----------------------------------------


Changed status from initializing to running.

Loading config file: /home/vr/code/pepatac/pipelines/pepatac.yaml


In [3]: pm.config.resources.get("genome_config")                                                                                                                                                            
Out[3]: '/home/vr/refgenie.yaml'

In [4]: pypiper.__version__                                                                                                                                                                                 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-3ec469bc8add> in <module>
----> 1 pypiper.__version__

NameError: name 'pypiper' is not defined

In [5]: import pypiper                                                                                                                                                                                      

In [6]: pypiper.__version__                                                                                                                                                                                 
Out[6]: '0.11.1'

In [7]: import attmap                                                                                                                                                                                       

In [8]: attmap.__version__                                                                                                                                                                                  
Out[8]: '0.12.5'

```

**Comment by vreuter** [comment]
```
In [9]: pm.config.resources                                                                                                                                                                                 
Out[9]: 
EchoAttMap
genome_config: ${REFGENIE}
adapters: null

```

**Comment by nsheff** [comment]
> Nevermind. In my quick test I hadn't reexported REFGENIE. That resolves that, but new error.
> 
> ```
> Traceback (most recent call last):
>   File "pipelines/pepatac.py", line 1550, in <module>
>     sys.exit(main())
>   File "pipelines/pepatac.py", line 503, in main
>     res = _add_resources(args, res)
>   File "pipelines/pepatac.py", line 457, in _add_resources
>     rgc = RGC(select_genome_config(res.get("genome_config")))
>   File "/home/jps3dp/.local/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 57, in __init__
>     raise MissingConfigDataError(CFG_SERVER_KEY)
> refgenconf.exceptions.MissingConfigDataError: genome_server
> Pipeline status: running
> Starting cleanup: 0 files; 0 conditional files for cleanup
> 
> ### Pipeline failed at:  (06-06 16:06:56) elapsed: 0.0 _TIME_
> ```
> 
> This looks simpler. Where do I set my server key?

don't edit an old comment to make a complete change in the message -- this new message will be lost because edits aren't notified. only make minor clarification edits and post a new idea as a new message.

your refgenie.yaml file needs a `genome_server` attribute (top-level attribute)

**Comment by nsheff** [comment]
@jpsmith5 let us know if just putting the `genome_server` into your refgenie file solves this.

but this brings up a point: maybe the `genome_server` attribute shouldn't be required. @vreuter what do you think? Is it intentional that `genome_server` is required? I can imagine a situation where it would not be needed (someone building and listing their own local assets). in fact, this is a good example case... the server isn't really necessarily required here to just tell us where the local bowtie index is...

**Comment by vreuter** [comment]
> but this brings up a point: maybe the `genome_server` attribute shouldn't be required. @vreuter what do you think? Is it intentional that `genome_server` is required?

I don't have a preference; it's required based on [this comment](https://github.com/databio/refgenconf/issues/21#issuecomment-498404380)
