### ISSUE TITLE
pararead import error

### ISSUE THREAD

**Issue by mbardus** [databio/pepatac#124]
When I run the pepatac on the test example I get the errors:
1. ImportError: cannot import name add_logging_options
2. ImportError: cannot import name logger_via_cli

changing the lines:
from pararead import add_logging_options
from pararead import logger_via_cli

into:
from logmuse import add_logging_options
from logmuse import logger_via_cli

it works.

**Comment by gbloeb** [comment]
I have similar errors:

### Calculate NRF, PBC1, and PBC2 (02-22 21:57:54) elapsed: 63.0 _TIME_

Target to produce: `/wynton/home/reiter/gloeb/pepatac_test/test1/QC_hg38/test1_bamQC.tsv`  

> `/wynton/home/reiter/gloeb/pepatac_tutorial/tools/pepatac/tools/bamQC.py -i /wynton/home/reiter/gloeb/pepatac_test/test1/aligned_hg38/test1_sort.bam -c 1 -o /wynton/home/reiter/gloeb/pepatac_test/test1/QC_hg38/test1_bamQC.tsv` (24630)
<pre>
Traceback (most recent call last):
  File "/wynton/home/reiter/gloeb/pepatac_tutorial/tools/pepatac/tools/bamQC.py", line 17, in <module>
    from pararead import add_logging_options, ParaReadProcessor
ImportError: cannot import name add_logging_options
</pre>
Command completed. Elapsed time: 0:00:04. Running peak memory: 3.064GB.  
  PID: 24630;	Command: /wynton/home/reiter/gloeb/pepatac_tutorial/tools/pepatac/tools/bamQC.py;	Return code: 1;	Memory used: 0.007GB

Child process 24003 (perl) was already terminated.
Child process 24110 (perl) was already terminated.
Starting cleanup: 6 files; 3 conditional files for cleanup

Cleaning up flagged intermediate files. . .

Conditional flag found: []

These conditional files were left in place:

- /wynton/home/reiter/gloeb/pepatac_test/test1/fastq/test1*.fastq
- /wynton/home/reiter/gloeb/pepatac_test/test1/fastq/*.fq
- /wynton/home/reiter/gloeb/pepatac_test/test1/fastq/*.log
- /wynton/home/reiter/gloeb/pepatac_test/test1/prealignments/tmpAC3WYH
- /wynton/home/reiter/gloeb/pepatac_test/test1/prealignments/rCRSd_bt2
- /wynton/home/reiter/gloeb/pepatac_test/test1/prealignments/tmpICCT5N
- /wynton/home/reiter/gloeb/pepatac_test/test1/prealignments/human_repeats_bt2
- /wynton/home/reiter/gloeb/pepatac_test/test1/aligned_hg38/tmp9FkmHl
- /wynton/home/reiter/gloeb/pepatac_test/test1/aligned_hg38/test1_temp.bam.bai

### Pipeline failed at:  (02-22 21:57:58) elapsed: 4.0 _TIME_

Total time: 0:01:53
Failure reason: Subprocess returned nonzero result. Check above output for details
Traceback (most recent call last):
  File "/wynton/home/reiter/gloeb/pepatac_tutorial/tools/pepatac/pipelines/pepatac.py", line 1422, in <module>
    sys.exit(main())
  File "/wynton/home/reiter/gloeb/pepatac_tutorial/tools/pepatac/pipelines/pepatac.py", line 866, in main
    container=pm.container)
  File "/wynton/home/reiter/gloeb/miniconda3/envs/pepatac/lib/python2.7/site-packages/pypiper/manager.py", line 785, in run
    self.callprint(cmd, shell, lock_file, nofail, container)  # Run command
  File "/wynton/home/reiter/gloeb/miniconda3/envs/pepatac/lib/python2.7/site-packages/pypiper/manager.py", line 1028, in callprint
    self._triage_error(SubprocessError(msg), nofail)
  File "/wynton/home/reiter/gloeb/miniconda3/envs/pepatac/lib/python2.7/site-packages/pypiper/manager.py", line 2131, in _triage_error
    self.fail_pipeline(e)
  File "/wynton/home/reiter/gloeb/miniconda3/envs/pepatac/lib/python2.7/site-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
pypiper.exceptions.SubprocessError: Subprocess returned nonzero result. Check above output for details
