### ISSUE TITLE
Updating to refgenie

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#127]
PEPATAC is not using refgenie correctly (it's still based on the old system I think).

```
Total time: 0:00:00
Failure reason: Could not find the 'hg38' index at: /ext/qumulo/genomes/hg38/indexed_bowtie2
Try updating/confirming the 'genomes' variable in 'pipelines/pepatac.yaml'.
Confirm that 'hg38' is the correct genome.
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1422, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 503, in main
    _check_bowtie2_index(res.genomes, args.genome_assembly)
  File "pipelines/pepatac.py", line 344, in _check_bowtie2_index
    loc_msg, typ_msg)))
  File "/home/nsheff/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
IOError: Could not find the 'hg38' index at: /ext/qumulo/genomes/hg38/indexed_bowtie2
Try updating/confirming the 'genomes' variable in 'pipelines/pepatac.yaml'.
Confirm that 'hg38' is the correct genome.
```

**Comment by nsheff** [comment]
actually I believe this is solved on dev.

@jpsmith5  That dev branch is really getting stale, we need to do a release of pepatac.

**Comment by jpsmith5** [comment]
Agreed. Will make testing the stability of dev a priority to get a release out as quickly as possible.
