### ISSUE TITLE
PEPATAC error: ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by taherimo** [databio/pepatac#165]
To install and run PEPATC I followed this guide: https://pepatac.databio.org/en/latest/install/. I think I did every step right. But when I run the following command:

```
cd pepatac
looper run -d examples/test_project/test_config.yaml
```

I receive this error:

```
Looper version: 1.3.0
Command: run
ProjectContext pipeline_interfaces: '['/home/ptaklifi/pepatac/sample_pipeline_interface.yaml']'
Traceback (most recent call last):
  File "/home/ptaklifi/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/looper/looper.py", line 743, in main
    run(args, rerun=(args.command == "rerun"), **compute_kwargs)
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/looper/looper.py", line 308, in __call__
    for schema_file in self.prj.get_schemas(self.prj.pipeline_interfaces)]
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/looper/looper.py", line 308, in <listcomp>
    for schema_file in self.prj.get_schemas(self.prj.pipeline_interfaces)]
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/eido/eido.py", line 209, in validate_config
    schema_dicts = read_schema(schema=schema)
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/eido/eido.py", line 139, in read_schema
    return _recursively_read_schemas(_load_yaml(schema), schema_list)
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/eido/eido.py", line 130, in _recursively_read_schemas
    lst.extend(read_schema(sch))
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/eido/eido.py", line 139, in read_schema
    return _recursively_read_schemas(_load_yaml(schema), schema_list)
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/yacman/yacman.py", line 291, in load_yaml
    response = urlopen(filepath)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

I searched a lot but could not find out what is the solution. May anyone please help me in this issue?

**Comment by stolarczyk** [comment]
hi @taherimo, unfortunately, I can't reproduce this error. Looking at the traceback you pasted here, there is an issue with reading a _remote_ schema (simple YAML file), which is imported in the [`pepatac_input_schema.yaml`](https://github.com/databio/pepatac/blob/3291788027375c57fbf76ed36ffd9349a8c463bc/pepatac_input_schema.yaml#L2-L3).

Can you check if you can read this remote file with `eido.read_schema`or [`urlopen`](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen)? For example:

```python
In [7]: from eido import read_schema                                                                                                                                                                      

In [8]: schemas = read_schema("../pepatac/pepatac_input_schema.yaml")                                                                                                                                     

In [9]: schemas                                                                                                                                                                                           
Out[9]: 
[{'description': 'Schema for a minimal PEP',
  'version': '2.0.0',
  'properties': {'name': {'type': 'string',
    'pattern': '^\\S*$',
    'description': 'Project name with no whitespace'},
   'config': {'pep_version': {'description': 'Version of the PEP Schema this PEP follows',
     'type': 'string'},
    'sample_table': {'type': 'string',
     'description': 'Path to the sample annotation table with one row per sample'},
    'subsample_table': {'type': 'string',
     'description': 'Path to the subsample annotation table with one row per subsample and sample_name attribute matching an entry in the sample table'},
    'sample_modifiers': {'type': 'object',
     'properties': {'append': {'type': 'object'},
      'duplicate': {'type': 'object'},
      'imply': {'type': 'array',
       'items': {'type': 'object',
        'properties': {'if': {'type': 'object'}, 'then': {'type': 'object'}}}},
      'derive': {'type': 'object',
       'properties': {'attributes': {'type': 'array',
         'items': {'type': 'string'}},
        'sources': {'type': 'object'}}}}},
    'project_modifiers': {'type': 'object',
     'properties': {'amend': {'description': 'Object overwriting original project attributes',
       'type': 'object'},
      'import': {'description': 'List of external PEP project config files to import',
       'type': 'array',
       'items': {'type': 'string'}}}},
    'required': ['pep_version']},
   'samples': {'type': 'array',
    'items': {'type': 'object',
     'properties': {'sample_name': {'type': 'string',
       'pattern': '^\\S*$',
       'description': 'Unique name of the sample with no whitespace'}},
     'required': ['sample_name']}}},
  'required': ['samples']},
 {'description': 'A PEP for ATAC-seq samples for the PEPATAC pipeline.',
  'imports': ['http://schema.databio.org/pep/2.0.0.yaml'],
  'properties': {'samples': {'type': 'array',
    'items': {'type': 'object',
     'properties': {'sample_name': {'type': 'string',
       'description': 'Name of the sample'},
      'organism': {'type': 'string', 'description': 'Organism'},
      'protocol': {'type': 'string',
       'description': 'Must be an ATAC-seq or DNAse-seq sample'},
      'genome': {'type': 'string',
       'description': 'Refgenie genome registry identifier'},
      'prealignments': {'type': ['string', 'array'],
       'descrption': 'Refgenie genome registry identifiers'},
      'read_type': {'type': 'string',
       'description': 'Is this single or paired-end data?',
       'enum': ['SINGLE', 'single', 'PAIRED', 'paired']},
      'read1': {'type': 'string', 'description': 'Fastq file for read 1'},
      'read2': {'type': 'string',
       'description': 'Fastq file for read 2 (for paired-end experiments)'},
      'extend': {'type': 'string',
       'description': 'Length to extend fixed width peaks around summit'},
      'frip_ref_peaks': {'type': 'string',
       'description': 'Path to a reference peak set'},
      'aligner': {'type': 'string',
       'description': 'Specify the read alignment tool',
       'enum': ['bowtie2', 'bwa']},
      'peak_caller': {'type': 'string',
       'description': 'Specify the peak calling tool',
       'enum': ['fseq', 'genrich', 'hmmratac', 'homer', 'macs2']},
      'genome_size': {'type': 'string',
       'description': 'MACS2 effective genome size'},
      'trimmer': {'type': 'string',
       'description': 'Specify the read trimming tool',
       'enum': ['trimmomatic', 'pyadapt', 'skewer']},
      'deduplicator': {'type': 'string',
       'description': 'Specify the read deduplication tool',
       'enum': ['picard', 'samblaster', 'samtools']},
      'peak_type': {'type': 'string',
       'description': 'Call variable or fixed width peaks',
       'enum': ['fixed', 'variable']},
      'anno_name': {'type': 'string',
       'description': 'Genomic partitions annotation file (by default uses Refgenie asset)'},
      'blacklist': {'type': 'string',
       'description': 'Path to file of blacklisted genomic regions (by default uses Refgenie asset)'},
      'TSS_name': {'type': 'string',
       'description': 'TSS annotation file (by default uses Refgenie asset)'},
      'motif': {'type': 'boolean',
       'description': 'Use HOMER to perform motif enrichment analysis'},
      'sob': {'type': 'boolean',
       'description': 'Use seqOutBias to generate signal tracks'},
      'no_scale': {'type': 'boolean',
       'description': 'Do not scale signal tracks'},
      'prioritize': {'type': 'boolean',
       'description': 'Plot cFRiF/FRiF using mutually exclusive priority ranked features based on the order of feature appearance in the feature annotation asset'},
      'keep': {'type': 'boolean',
       'description': 'Keep prealignment BAM files'},
      'noFIFO': {'type': 'boolean',
       'description': 'Do NOT use named pipes during prealignments'},
      'lite': {'type': 'boolean',
       'description': 'Remove all intermediate file types'},
      'skipqc': {'type': 'boolean',
       'description': 'Do not use FastQC even if available'}},
     'required': ['sample_name', 'protocol', 'read1', 'genome'],
     'required_files': ['read1'],
     'files': ['read1', 'read2']}}},
  'required': ['samples']}]
```

**Comment by taherimo** [comment]
Thank you @stolarczyk for your reply.
When I run the commands you mentioned I get same error:

```
>>> from eido import read_schema
>>> schemas = read_schema("../pepatac/pepatac_input_schema.yaml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/eido/eido.py", line 139, in read_schema
    return _recursively_read_schemas(_load_yaml(schema), schema_list)
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/eido/eido.py", line 130, in _recursively_read_schemas
    lst.extend(read_schema(sch))
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/eido/eido.py", line 139, in read_schema
    return _recursively_read_schemas(_load_yaml(schema), schema_list)
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/yacman/yacman.py", line 291, in load_yaml
    response = urlopen(filepath)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1353, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.6/urllib/request.py", line 1328, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 272, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by nsheff** [comment]
Is it possible that your computing host is not allowing you to make external connections somehow? Can you do:

```
wget http://schema.databio.org/pep/2.0.0.yaml
```

or 

```
curl http://schema.databio.org/pep/2.0.0.yaml
```
?

@stolarczyk and @jpsmith5 -- Thinking about this further, I'm not sure it makes sense to query away to the web for this. This effectively makes it impossible to use this pipeline on a server that is not connected to the internet, right? Does it make sense to either 1) include this schema locally or 2) write in a fallback option somehow?

**Comment by stolarczyk** [comment]
Having a local, version-controlled schema makes sense to me. Eido is already equipped to deal with local elements in the `imports` list, so that would be a change in this repo.

**Comment by nsheff** [comment]
Thanks @taherimo -- so you can see there, the issue is that your server is not allowing external http connections. You can ask your sysadmin about that.

In the meantime, a way around it is to download that file, and change this line to point to the local file:

https://github.com/databio/pepatac/blob/3291788027375c57fbf76ed36ffd9349a8c463bc/pepatac_input_schema.yaml#L3

You may be able to get away with just deleting the `imports` section from that schema, but you'd lose some of the type checking functionality. but that way you could see if the rest of the pipeline will run.

**Comment by taherimo** [comment]
Thank you @nsheff for your help. I found out that wget works with https rather than http.
Here is the result of `curl http://schema.databio.org/pep/2.0.0.yaml:`

`curl: (56) Recv failure: Connection reset by peer`

And here is the result of `curl https://schema.databio.org/pep/2.0.0.yaml`:

```
description: "Schema for a minimal PEP"
version: "2.0.0"
properties:
  name:
    type: string
    pattern: "^\\S*$"
    description: "Project name with no whitespace"
  config:
    pep_version:
      description: "Version of the PEP Schema this PEP follows"
      type: string
    sample_table:
      type: string
      description: "Path to the sample annotation table with one row per sample"
    subsample_table:
      type: string
      description: "Path to the subsample annotation table with one row per subsample and sample_name attribute matching an entry in the sample table"
    sample_modifiers:
      type: object
      properties:
        append:
          type: object
        duplicate:
          type: object
        imply:
          type: array
          items:
            type: object
            properties:
              if:
                type: object
              then:
                type: object
        derive:
          type: object
          properties:
            attributes:
              type: array
              items:
                type: string
            sources:
              type: object
    project_modifiers:
      type: object
      properties:
        amend:
          description: "Object overwriting original project attributes"
          type: object
        import:
          description: "List of external PEP project config files to import"
          type: array
          items:
            type: string
    required:
      - pep_version
  samples:
    type: array
    items:
      type: object
      properties:
        sample_name:
          type: string
          pattern: "^\\S*$"
          description: "Unique name of the sample with no whitespace"
      required:
        - sample_name
required:
  - samples
```
Is there any way to make PEPATAC to work with https instead of http?

**Comment by nsheff** [comment]
Sure, just change the URL to `https` in the input schema yaml file. The https link works: `https://schema.databio.org/pep/2.0.0.yaml`

that's line 3 in pepatac/pepatac_input_schema.yaml

**Comment by taherimo** [comment]
Thank you @nsheff -- I changed http to https in the file pepatac_input_schema.yaml. Now by running looper `run -d examples/test_project/test_config.yaml` I get the following error message:

```
Looper version: 1.3.0
Command: run
## [1 of 1] sample: test1; pipeline: PEPATAC
Writing script to /home/ptaklifi/pepatac/$PROCESSED/pepatac_test/submission/PEPATAC_test1.sub
ProjectContext pipeline_interfaces: '['/home/ptaklifi//pepatac/sample_pipeline_interface.yaml']'
Traceback (most recent call last):
  File "/home/ptaklifi/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/looper/looper.py", line 743, in main
    run(args, rerun=(args.command == "rerun"), **compute_kwargs)
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/looper/looper.py", line 351, in __call__
    curr_pl_fails = cndtr.add_sample(sample, rerun=rerun)
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/looper/conductor.py", line 365, in add_sample
    self.submit()
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/looper/conductor.py", line 402, in submit
    script = self.write_script(self._pool, self._curr_size)
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/looper/conductor.py", line 583, in write_script
    extra_vars=[{"looper": looper}])
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/divvy/compute.py", line 315, in write_script
    return write_submit_script(output_path, self.template(), variables)
  File "/home/ptaklifi/.local/lib/python3.6/site-packages/divvy/utils.py", line 94, in write_submit_script
    os.makedirs(outdir)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '$PROCESSED'
```

**Comment by stolarczyk** [comment]
great, the schema imprting worked well this time. 

```
PermissionError: [Errno 13] Permission denied: '$PROCESSED'
```

That's because you do not have `$PROCESSED` env var set. This is similar to https://github.com/databio/pepatac/issues/163 and related to #164

**Comment by taherimo** [comment]
Thank you @stolarczyk and @nsheff for your help. It works now.
