### ISSUE TITLE
fseq2 cannot be specified as a peak caller in PEPATAC v0.9.16

### ISSUE THREAD

**Issue by kwcurrin** [databio/pepatac#184]
Hello,

After updating to PEPATAC v0.9.16, I am no longer able to specify fseq2 as a peak caller. Now that the original fseq has been added back as a peak calling option, setting "peak_caller: fseq" in the config .yaml file results in the original fseq being used, as expected. However, I received the below error when specifying "peak_caller: fseq2":
(start of error)
Traceback (most recent call last):
  File "/<fseq2_install_dir>/2021-04/miniconda3/envs/fseq2_env/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/<fseq2_install_dir>/2021-04/miniconda3/envs/fseq2_env/lib/python3.7/site-packages/looper/looper.py", line 743, in main
    run(args, rerun=(args.command == "rerun"), **compute_kwargs)
  File "/<fseq2_install_dir>/2021-04/miniconda3/envs/fseq2_env/lib/python3.7/site-packages/looper/looper.py", line 339, in __call__
    for schema_file in self.prj.get_schemas(sample_pifaces)]
  File "/<fseq2_install_dir/2021-04/miniconda3/envs/fseq2_env/lib/python3.7/site-packages/looper/looper.py", line 339, in <listcomp>
    for schema_file in self.prj.get_schemas(sample_pifaces)]
  File "/<fseq2_install_dir>/2021-04/miniconda3/envs/fseq2_env/lib/python3.7/site-packages/eido/validation.py", line 82, in validate_sample
    sample=sample, schemas=read_schema(schema=schema), exclude_case=exclude_case
  File "/<fseq2_install_dir/2021-04/miniconda3/envs/fseq2_env/lib/python3.7/site-packages/eido/validation.py", line 62, in _validate_sample_object
    _validate_object(sample, sample_schema_dict, exclude_case)
  File "<fseq2_install_dir>/2021-04/miniconda3/envs/fseq2_env/lib/python3.7/site-packages/eido/validation.py", line 30, in _validate_object
    raise jsonschema.exceptions.ValidationError(e.message)
jsonschema.exceptions.ValidationError: 'fseq2' is not one of ['fseq', 'genrich', 'hmmratac', 'homer', 'macs2']
(end of error)

Thanks,

Kevin

**Comment by jpsmith5** [comment]
Same answer as #183. Will work to support fseq2 in future releases.
