### ISSUE TITLE
 No address associated with hostname

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#185]
@stolarczyk do you know what might cause this? Does it have to do with trying to import a config when there's no network connection?

Think we can improve the messaging here for eido? I can't figure out what's wrong with my setup that leads to this error

```
looper run examples/test_project/test_config.yaml
Looper version: 1.3.1-dev
Command: run
ProjectContext pipeline_interfaces: '['/home/nsheff/code/pepatac/sample_pipeline_interface.yaml']'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/local/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 987, in main
    run(args, rerun=(args.command == "rerun"), **compute_kwargs)
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 399, in __call__
    [validate_config(self.prj, schema_file, True)
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 399, in <listcomp>
    [validate_config(self.prj, schema_file, True)
  File "/home/nsheff/.local/lib/python3.8/site-packages/eido/validation.py", line 95, in validate_config
    schema_dicts = read_schema(schema=schema)
  File "/home/nsheff/.local/lib/python3.8/site-packages/eido/schema.py", line 69, in read_schema
    return _recursively_read_schemas(load_yaml(schema), schema_list)
  File "/home/nsheff/.local/lib/python3.8/site-packages/eido/schema.py", line 61, in _recursively_read_schemas
    lst.extend(read_schema(sch))
  File "/home/nsheff/.local/lib/python3.8/site-packages/eido/schema.py", line 69, in read_schema
    return _recursively_read_schemas(load_yaml(schema), schema_list)
  File "/home/nsheff/.local/lib/python3.8/site-packages/peppy/utils.py", line 125, in load_yaml
    response = urlopen(filepath)
  File "/usr/local/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1348, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -5] No address associated with hostname>
```

**Comment by nsheff** [comment]
I'm not actually sure why anything has to be validated at this stage, but it would probably be better to just give a warning if something remote can't be found rather than to fail catastrophically? the file is actually correct.

**Comment by stolarczyk** [comment]
Yes, there was no internet connection and that was the reason. 

I'm catching an HTTPError in the function loading the remote schema, but a different one is raised here.

**Comment by nsheff** [comment]
Ok so I think there are 3 things we need to do to solve this:

1. @jpsmith5 can you embed everything necessary so that PEPATAC doesn't require a remote connection to validate? I think we ran into this same problem with PEPPRO or something.
2. @stolarczyk can you make it so that  the error message in this case would be more understandable?
3. @stolarczyk I think looper should only fail catastrophically if the input *doesn't* validate -- if it simply *can't* validate it (*e.g.* because there's no network connection), it can still just try it. In this case it would have succeeded. So we shouldn't bail completely if the validation component isn't working.
