### ISSUE TITLE
tutorial to run from singularity is failing with this error:The following required tool(s) are not callable: macs2 

### ISSUE THREAD

**Issue by bioarpit1** [databio/pepatac#237]
hi 

I am trying to follow the tutorial for run from container. I am using latest docker image to make the sif image. but somehow its failing with the following required tools are not callable:macs2 

*              Command:  `/home/amishra/pepatac_tutorial/tools/pepatac/pipelines/pepatac.py --single-or-paired paired --prealignment-index rCRSd= /home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/rCRSd/bowtie2_index/default/rCRSd. --genome hg38 --genome-index /home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/hg38/bowtie2_index/default/hg38. --chrom-sizes /home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/hg38/fasta/default/hg38.chrom.sizes --sample-name test1 --input /home/amishra/pepatac_tutorial/tools/pepatac/examples/data/test1_r1.fastq.gz --input2 /home/amishra/pepatac_tutorial/tools/pepatac/examples/data/test1_r2.fastq.gz --genome-siz hs -O /home/amishra/pepatac_tutorial/`
*         Compute host:  SRV-SINGLE-01.BRIVMRC.ORG
*          Working dir:  /home/amishra
*            Outfolder:  /home/amishra/pepatac_tutorial/test1/
*  Pipeline started at:   (03-04 23:54:57) elapsed: 0.0 _TIME_

### Version log:

*       Python version:  3.10.6
*          Pypiper dir:  `/usr/local/lib/python3.10/dist-packages/pypiper`
*      Pypiper version:  0.12.3
*         Pipeline dir:  `/home/amishra/pepatac_tutorial/tools/pepatac/pipelines`
*     Pipeline version:  0.10.4
*        Pipeline hash:  756632d1bd9aae182eab10e34b294f08744663cc
*      Pipeline branch:  * master
*        Pipeline date:  2023-02-22 10:19:16 -0500
*        Pipeline diff:  2 files changed, 2 insertions(+), 2 deletions(-)

### Arguments passed to pipeline:

*           `TSS_name`:  `None`
*            `aligner`:  `bowtie2`
*          `anno_name`:  `None`
*          `blacklist`:  `None`
*        `chrom_sizes`:  `/home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/hg38/fasta/default/hg38.chrom.sizes`
*        `config_file`:  `pepatac.yaml`
*              `cores`:  `1`
*       `deduplicator`:  `samblaster`
*              `dirty`:  `False`
*             `extend`:  `250`
*              `fasta`:  `None`
*       `force_follow`:  `False`
*     `frip_ref_peaks`:  `None`
*    `genome_assembly`:  `hg38`
*       `genome_index`:  `/home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/hg38/bowtie2_index/default/hg38.`
*        `genome_size`:  `hs`
*              `input`:  `['/home/amishra/pepatac_tutorial/tools/pepatac/examples/data/test1_r1.fastq.gz']`
*             `input2`:  `['/home/amishra/pepatac_tutorial/tools/pepatac/examples/data/test1_r2.fastq.gz']`
*               `keep`:  `False`
*               `lite`:  `False`
*             `logdev`:  `False`
*                `mem`:  `4000`
*              `motif`:  `False`
*          `new_start`:  `False`
*            `no_fifo`:  `False`
*           `no_scale`:  `False`
*      `output_parent`:  `/home/amishra/pepatac_tutorial/`
*         `paired_end`:  `True`
*        `peak_caller`:  `macs2`
*          `peak_type`:  `fixed`
* `prealignment_index`:  `['rCRSd=', '/home/amishra/pepatac_tutorial/tools/pepatac/genome_folder/alias/rCRSd/bowtie2_index/default/rCRSd.']`
* `prealignment_names`:  `[]`
*         `prioritize`:  `False`
*            `recover`:  `False`
*        `sample_name`:  `test1`
*        `search_file`:  `None`
*             `silent`:  `False`
*   `single_or_paired`:  `paired`
*             `skipqc`:  `False`
*                `sob`:  `False`
*           `testmode`:  `False`
*            `trimmer`:  `skewer`
*          `verbosity`:  `None`

----------------------------------------

The following required tool(s) are not callable: macs2

### Pipeline failed at:  (03-04 23:54:57) elapsed: 0.0 _TIME_

Total time: 0:00:00
Failure reason: Missing required tools. See message above.
Traceback (most recent call last):
  File "/home/amishra/pepatac_tutorial/tools/pepatac/pipelines/pepatac.py", line 2779, in <module>
    sys.exit(main())
  File "/home/amishra/pepatac_tutorial/tools/pepatac/pipelines/pepatac.py", line 602, in main
    pm.fail_pipeline(RuntimeError(err_msg))
  File "/usr/local/lib/python3.10/dist-packages/pypiper/manager.py", line 1660, in fail_pipeline
    raise exc
RuntimeError: Missing required tools. See message above.

**Comment by 2lore** [comment]
I had the same issue in docker when I pulled the most recent pepatac image.
The workaround I used now is going back to an earlier version of the pepatac image in docker (0.10.0) - then the pipeline runs without this error.

**Comment by Suncuss** [comment]
I am having similar issue with the docker image too

**Comment by jpsmith5** [comment]
Containerized installation paths (Docker/Singularity) were removed in PEPATAC 0.12.0 (Jan 2025). The supported install paths are now `bulker` (which manages per-tool containers transparently — see [run-bulker](https://pepatac.databio.org/en/latest/run-bulker/)), conda (`requirements-conda.yml`), or native install. Closing as obsolete; if you're still hitting an issue against one of the current paths, please reopen with logs from the latest release.
