### ISSUE TITLE
PEPATAC incompatible with pypiper stats.yaml file

### ISSUE THREAD

**Issue by DQ-Zhang** [databio/pepatac#254]
Following Databio/pypiper#188, pypiper reports statistics in a stats.yaml file instead of a stats.tsv file. However, PEPATACr still parses stats.tsv file in output directories of respective samples to create summary stats. 

In PEPATAC/PEPATACr/R/PEPATACr.R

 ```
createStatsSummary <- function(samples, results_subdir) {  
     # Create stats_summary file
     missing_files   <- 0
     write(paste0("Creating stats summary..."), stdout())

    for (sample in samples) {
        sample_output_folder <- file.path(results_subdir, sample)
        sample_assets_file   <- file.path(sample_output_folder, "stats.tsv")

        if (!file.exists(sample_assets_file)) {
            missing_files <- missing_files + 1
            next
        }

        t <- fread(sample_assets_file, header=FALSE,
                   col.names=c('stat', 'val', 'annotation'))
        # Remove complete duplicates
        t <- t[!duplicated(t[, c('stat', 'val', 'annotation')],
               fromLast=TRUE),]
        max_time <- suppressWarnings(max(t[stat=="Time",]$val))
        # Keep max(Time) and last(Success)
        t <- t[!duplicated(t[, c('stat', 'annotation')],
               fromLast=TRUE),]
        t[stat=="Time",]$val <- max_time

        t2 <- data.table(t(t$val))
        colnames(t2) <- t$stat
        t2 <- cbind(data.table(sample_name=sample), t2)
        if (exists("stats")) {
            stats <- rbind(stats, t2, fill=TRUE)
        } else {
            stats <- t2
        }
    }

    if (missing_files > 0) {
        warning(sprintf("Stats files missing for %s samples.", missing_files))
    }

    return(stats)
}`
 ```
This leads to an error while running the PEPATAC project pipeline.

Command:
`looper runp project_config_test.yaml`

PEPATAC_collator_log.md
 ```
### Pipeline run code and environment:

*              Command:  `/mnt/g/ATAC/pepatac/tools/pepatac/pipelines/pepatac_collator.py --config project_config_test.yaml -O /mnt/g/ATAC/pepatac/output_test -P 1 -M 16000 -n Test -r /mnt/g/ATAC/pepatac/output_test/results_pipeline`
*         Compute host:  DESKTOP-BCM1PG4
*          Working dir:  /mnt/g/ATAC/pepatac
*            Outfolder:  /mnt/g/ATAC/pepatac/output_test/summary/
*  Pipeline started at:   (11-07 18:39:32) elapsed: 0.0 _TIME_

### Version log:

*       Python version:  3.9.7
*          Pypiper dir:  `/home/dingqi/miniconda3/envs/pepatac/lib/python3.9/site-packages/pypiper`
*      Pypiper version:  0.13.2
*         Pipeline dir:  `/mnt/g/ATAC/pepatac/tools/pepatac/pipelines`
*     Pipeline version:  0.0.4
*        Pipeline hash:  9ee0b6c1251b1addae8265c12f16cbfeae76d489
*      Pipeline branch:  * master
*        Pipeline date:  2023-07-31 17:32:28 -0400
*        Pipeline diff:  2 files changed, 43 insertions(+), 4 deletions(-)

### Arguments passed to pipeline:

*        `config_file`:  `project_config_test.yaml`
*              `cores`:  `1`
*             `cutoff`:  `2`
*              `dirty`:  `False`
*       `force_follow`:  `False`
*             `logdev`:  `False`
*                `mem`:  `16000`
*           `min_olap`:  `1`
*          `min_score`:  `5`
*               `name`:  `Test`
*          `new_start`:  `False`
*         `normalized`:  `False`
*      `output_parent`:  `/mnt/g/ATAC/pepatac/output_test`
*      `pipeline_name`:  `None`
*           `poverlap`:  `False`
*            `recover`:  `False`
*            `results`:  `/mnt/g/ATAC/pepatac/output_test/results_pipeline`
*             `silent`:  `False`
*     `skip_consensus`:  `False`
*         `skip_table`:  `False`
*           `testmode`:  `False`
*          `verbosity`:  `None`

### Initialized Pipestat Object:

* PipestatManager (PEPATAC_collator)
* Backend: File
*  - results: /mnt/g/ATAC/pepatac/output_test/summary/stats.yaml
*  - status: /mnt/g/ATAC/pepatac/output_test/summary
* Multiple Pipelines Allowed: False
* Pipeline name: PEPATAC_collator
* Pipeline type: sample
* Status Schema key: None
* Results formatter: default_formatter
* Results schema source: None
* Status schema source: None
* Records count: 2
* Sample name: DEFAULT_SAMPLE_NAME


----------------------------------------

Target to produce: `/mnt/g/ATAC/pepatac/output_test/summary/Test_libComplexity.pdf`,`/mnt/g/ATAC/pepatac/output_test/summary/Test_*_consensusPeaks.narrowPeak`,`/mnt/g/ATAC/pepatac/output_test/summary/Test_peaks_coverage.tsv`  

> `Rscript /mnt/g/ATAC/pepatac/tools/pepatac/tools/PEPATAC_summarizer.R project_config_test.yaml /mnt/g/ATAC/pepatac/output_test /mnt/g/ATAC/pepatac/output_test/results_pipeline 2 5 1` (15532)
<pre>
Loading config file: /mnt/g/ATAC/pepatac/project_config_test.yaml
Creating stats summary...
Error in setnames(ans, col.names) : 
  Can't assign 3 names to a 2 column data.table
Calls: <Anonymous> -> fread -> setnames
In addition: Warning message:
In fread(sample_assets_file, header = FALSE, col.names = c("stat",  :
  Stopped early on line 12. Expected 2 fields but found 9. Consider fill=TRUE and comment.char=. First discarded non-empty line: <<FastQC report r1: fastq/B1_R1_trim_fastqc.html FastQC report r1 None PEPATAC>>
Execution halted
</pre>
Command completed. Elapsed time: 0:00:03. Running peak memory: 0.115GB.  
  PID: 15532;	Command: Rscript;	Return code: 1;	Memory used: 0.115GB

Using default schema: /mnt/g/ATAC/pepatac/tools/pepatac/pipelines/pipestat_output_schema.yaml

### Pipeline failed at:  (11-07 18:39:34) elapsed: 3.0 _TIME_

Total time: 0:00:03
Failure reason: Subprocess returned nonzero result. Check above output for details
Traceback (most recent call last):
  File "/mnt/g/ATAC/pepatac/tools/pepatac/pipelines/pepatac_collator.py", line 101, in <module>
    sys.exit(main())
  File "/mnt/g/ATAC/pepatac/tools/pepatac/pipelines/pepatac_collator.py", line 95, in main
    pm.run(cmd, [complexity_file, consensus_peaks_file, peak_coverage_file])
  File "/home/dingqi/miniconda3/envs/pepatac/lib/python3.9/site-packages/pypiper/manager.py", line 1073, in run
    process_return_code, local_maxmem = self.callprint(
  File "/home/dingqi/miniconda3/envs/pepatac/lib/python3.9/site-packages/pypiper/manager.py", line 1342, in callprint
    self._triage_error(SubprocessError(msg), nofail)
  File "/home/dingqi/miniconda3/envs/pepatac/lib/python3.9/site-packages/pypiper/manager.py", line 2565, in _triage_error
    self.fail_pipeline(e)
  File "/home/dingqi/miniconda3/envs/pepatac/lib/python3.9/site-packages/pypiper/manager.py", line 2036, in fail_pipeline
    raise exc
pypiper.exceptions.SubprocessError: Subprocess returned nonzero result. Check above output for details
 ```

Please fix this.

**Comment by donaldcampbelljr** [comment]
This is now fixed with v0.11.0 release.
