### ISSUE TITLE
pypiper.exceptions.SubprocessError: Subprocess returned nonzero result.

### ISSUE THREAD

**Issue by zhongzheng1999** [databio/pepatac#270]
[test1_rCRSd_bt_aln_summary.log](https://github.com/databio/pepatac/files/14096432/test1_rCRSd_bt_aln_summary.log)

[PEPATAC_test1.log](https://github.com/databio/pepatac/files/14096427/PEPATAC_test1.log)

I hope this message finds you well. I am reaching out to report an issue I encountered while running the PEPATAC test file using the command "`looper run examples/test_project/test_config.yaml.`" The error message I received is as follows:

> ### Pipeline failed at:  (01-30 18:23:32) elapsed: 1.0 _TIME_
> 
> Total time: 0:00:13
> Failure reason: Subprocess returned nonzero result. Check above output for details
> Traceback (most recent call last):
>   File "/home/u2204084007/biosoft/pepatac-0.11.2/pipelines/pepatac.py", line 2779, in <module>
>     sys.exit(main())
>   File "/home/u2204084007/biosoft/pepatac-0.11.2/pipelines/pepatac.py", line 971, in main
>     unmap_fq1, unmap_fq2 = _align(
>   File "/home/u2204084007/biosoft/pepatac-0.11.2/pipelines/pepatac.py", line 387, in _align
>     pm.run(cmd, [summary_file, out_fastq_r2_gz])
>   File "/home/u2204084007/mambaforge/envs/pepatac/lib/python3.9/site-packages/pypiper/manager.py", line 1083, in run
>     process_return_code, local_maxmem = self.callprint(
>   File "/home/u2204084007/mambaforge/envs/pepatac/lib/python3.9/site-packages/pypiper/manager.py", line 1352, in callprint
>     self._triage_error(SubprocessError(msg), nofail)
>   File "/home/u2204084007/mambaforge/envs/pepatac/lib/python3.9/site-packages/pypiper/manager.py", line 2575, in _triage_error
>     self.fail_pipeline(e)
>   File "/home/u2204084007/mambaforge/envs/pepatac/lib/python3.9/site-packages/pypiper/manager.py", line 2045, in fail_pipeline
>     raise exc
> pypiper.exceptions.SubprocessError: Subprocess returned nonzero result. Check above output for details

I have uploaded the corresponding log file for your reference.

Upon further investigation, I suspect the error may be related to prealignments. In the log file "test1_rCRSd_bt_aln_summary.log" within the "prealignments" folder, the following message is present:

> "default/94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4" does not exist or is not a Bowtie 2 index.

However, I want to highlight that I have executed the following commands:
```
refgenie pull rCRSd/bowtie2_index
refgenie seek rCRSd/bowtie2_index.dir
```

Despite these commands being run, it seems that there is an issue with the Bowtie 2 index. I would appreciate your assistance in resolving this matter. If you require additional information or logs, please let me know, and I will promptly provide them.

Thank you for your attention to this matter.

**Comment by zhongzheng1999** [comment]
I must admit, I made a somewhat amusing mistake that left me both laughing and crying.  I naively believed that the `refgenie seek` command would automatically update the content of the bowtie2 index location in the `yaml` file. However, it turns out that I need to manually modify this location in the `yaml` file. Lesson learned!
