### ISSUE TITLE
MACS3 not in the bulker/singularity container

### ISSUE THREAD

**Issue by sunta3iouxos** [databio/pepatac#284]
Hi all,
Thank you for this tool.
I am trying to set it in our HPC server and I am having a bit of difficulties. On think I noticed is that MACS3 is missing from the /bulker/singularity/docker container.
This is the error I got:
```bash
databio/pepatac|~/pepatac$ pipelines/pepatac.py --single-or-paired paired \
2 examples/data/>   --prealignment-index /scratch/tgeorgom/refgenie/alias/rCRSd/bowtie2_index/default/. \
>   --genome hg38 \
>   --genome-index /scratch/tgeorgom/refgenie/alias/hg38/bowtie2_index/default/. \
>   --chrom-sizes /scratch/tgeorgom/refgenie/alias/hg38/fasta/default/hg38.chrom.sizes \
>   --sample-name test1 \
>   --input examples/data/test1_r1.fastq.gz \
>   --input2 examples/data/test1_r2.fastq.gz \
>   --genome-size hs \
>   -O $HOME/pepatac_test
Using default schema: pipelines/pipestat_output_schema.yaml
No pipestat output schema was supplied to PipestatManager.
Initializing results file '/home/tgeorgom/pepatac_test/test1/stats.yaml'
### Pipeline run code and environment:

*          Command: `pipelines/pepatac.py --single-or-paired paired --prealignment-index /scratch/tgeorgom/refgenie/alias/rCRSd/bowtie2_index/default/. --genome hg38 --genome-index /scratch/tgeorgom/refgenie/alias/hg38/bowtie2_index/default/. --chrom-sizes /scratch/tgeorgom/refgenie/alias/hg38/fasta/default/hg38.chrom.sizes --sample-name test1 --input examples/data/test1_r1.fastq.gz --input2 examples/data/test1_r2.fastq.gz --genome-size hs -O /home/tgeorgom/pepatac_test`
*     Compute host: `cheops1`
*      Working dir: `/home/tgeorgom/pepatac`
*        Outfolder: `/home/tgeorgom/pepatac_test/test1/`
*         Log file: `/home/tgeorgom/pepatac_test/test1/PEPATAC_log.md`
*       Start time:  (09-25 08:28:26) elapsed: 5.0 _TIME_

### Version log:

*   Python version: `3.10.14`
*      Pypiper dir: `/home/tgeorgom/miniforge3/lib/python3.10/site-packages/pypiper`
*  Pypiper version: `0.14.2`
*     Pipeline dir: `/home/tgeorgom/pepatac/pipelines`
* Pipeline version: `0.11.3`
*    Pipeline hash: `82f0685e4d98d71d6d2fc5acfc9b995877c91648`
*  Pipeline branch: `* master`
*    Pipeline date: `2024-06-05 14:59:51 -0400`
*    Pipeline diff: `1 file changed, 21 insertions(+), 21 deletions(-)`

### Arguments passed to pipeline:

*           `TSS_name`:  `None`
*            `aligner`:  `bowtie2`
*          `anno_name`:  `None`
*          `blacklist`:  `None`
*        `chrom_sizes`:  `/scratch/tgeorgom/refgenie/alias/hg38/fasta/default/hg38.chrom.sizes`
*        `config_file`:  `pepatac.yaml`
*              `cores`:  `1`
*       `deduplicator`:  `samblaster`
*              `dirty`:  `False`
*             `extend`:  `250`
*              `fasta`:  `None`
*       `force_follow`:  `False`
*     `frip_ref_peaks`:  `None`
*    `genome_assembly`:  `hg38`
*       `genome_index`:  `/scratch/tgeorgom/refgenie/alias/hg38/bowtie2_index/default/.`
*        `genome_size`:  `hs`
*              `input`:  `['examples/data/test1_r1.fastq.gz']`
*             `input2`:  `['examples/data/test1_r2.fastq.gz']`
*               `keep`:  `False`
*               `lite`:  `False`
*             `logdev`:  `False`
*                `mem`:  `4000`
*              `motif`:  `False`
*          `new_start`:  `False`
*            `no_fifo`:  `False`
*           `no_scale`:  `False`
*      `output_parent`:  `/home/tgeorgom/pepatac_test`
*         `paired_end`:  `True`
*        `peak_caller`:  `macs3`
*          `peak_type`:  `fixed`
*      `pipeline_name`:  `None`
* `prealignment_index`:  `['/scratch/tgeorgom/refgenie/alias/rCRSd/bowtie2_index/default/.']`
* `prealignment_names`:  `[]`
*         `prioritize`:  `False`
*            `recover`:  `False`
*        `sample_name`:  `test1`
*        `search_file`:  `None`
*             `silent`:  `False`
*   `single_or_paired`:  `paired`
*             `skipqc`:  `False`
*                `sob`:  `False`
*           `testmode`:  `False`
*            `trimmer`:  `skewer`
*          `verbosity`:  `None`

### Initialized Pipestat Object:

* PipestatManager (default_pipeline_name)
* Backend: File
*  - results: /home/tgeorgom/pepatac_test/test1/stats.yaml
*  - status: /home/tgeorgom/pepatac_test/test1
* Multiple Pipelines Allowed: False
* Pipeline name: default_pipeline_name
* Pipeline type: sample
* Status Schema key: None
* Results formatter: default_formatter
* Results schema source: None
* Status schema source: None
* Records count: 2
* Sample name: DEFAULT_SAMPLE_NAME


----------------------------------------

The following required tool(s) are not callable: macs3

### Pipeline failed at:  (09-25 08:28:26) elapsed: 1.0 _TIME_

Total time: 0:00:05
Failure reason: Missing required tools. See message above.
Traceback (most recent call last):
  File "/home/tgeorgom/pepatac/pipelines/pepatac.py", line 2779, in <module>
    sys.exit(main())
  File "/home/tgeorgom/pepatac/pipelines/pepatac.py", line 602, in main
    pm.fail_pipeline(RuntimeError(err_msg))
  File "/home/tgeorgom/miniforge3/lib/python3.10/site-packages/pypiper/manager.py", line 2009, in fail_pipeline
    raise exc
RuntimeError: Missing required tools. See message above.
```

**Comment by nsheff** [comment]
macs3 is in the latest bulker crate. possibly the documentation didn't get correctly updated. Which version of the pepatac bulker crate are you using?

You can use:

```
bulker activate databio/pepatac:1.0.11
macs3
```

**Comment by sunta3iouxos** [comment]
Hi there, this is my version, per readthedoc instruction:
```bulker activate databio/pepatac:1.0.7```
maybe this also needs to be activated?

**Comment by nsheff** [comment]
Yes, looks like the docs need to be updated. Sorry about that.

**Comment by nsheff** [comment]
I updated the docs for future users.

**Comment by sunta3iouxos** [comment]
Nice, thank you for being active.
I hope I will resolve all issues as soon as possible and get this nice
script running.
