### ISSUE TITLE
Bad error message

### ISSUE THREAD

**Issue by nsheff** [databio/pepatac#292]
If your pipeline_interface path does not exist, you get this non-intuitive error:

```
looper run -d
Looper version: 2.0.0a2
Command: run
Pipeline interface not found at given path: /home/ns5bc/code/pepatac/pipeline_interface.yaml
Using looper config (.looper.yaml).
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 8, in <module>
    sys.exit(main_cli())
             ^^^^^^^^^^
  File "/home/ns5bc/.local/lib/python3.11/site-packages/looper/cli_pydantic.py", line 357, in main_cli
    main()
  File "/home/ns5bc/.local/lib/python3.11/site-packages/looper/cli_pydantic.py", line 353, in main
    return run_looper(args, parser, test_args=test_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ns5bc/.local/lib/python3.11/site-packages/looper/cli_pydantic.py", line 232, in run_looper
    raise MisconfigurationException(
looper.exceptions.MisconfigurationException: `sample_pipeline_interface` is missing. Provide it in the parameters.
````

The exception should rather be something like "File not found exception"

**Comment by nsheff** [comment]
Oops, created in the wrong repo. Moved to here: https://github.com/pepkit/looper/issues/528
